export const secretchakra: IComponents = {
  root: {
    id: "root",
    parent: "root",
    type: "Box",
    children: ["comp-root"],
    props: {},
  },
  "comp-root": {
    id: "comp-root",
    props: {
      width: "100%",
      height: "100%",
      display: "flex",
      flexDirection: "column",
      color: "",
      backgroundColor: "gray.100",
    },
    children: ["comp-K74L6WFISOLG3", "comp-K74LORRCCHJDL"],
    type: "Flex",
    parent: "root",
    rootParentType: "Flex",
  },
  "comp-K74L6WFISOLG3": {
    id: "comp-K74L6WFISOLG3",
    props: {
      backgroundColor: "#1a202c",
      p: "3",
    },
    children: [
      "comp-K74L811LSF53G",
      "comp-K74LBAD12N7N8",
      "comp-K74LCUBUZD53Y",
    ],
    type: "Flex",
    parent: "comp-root",
    rootParentType: "Flex",
  },
  "comp-K74L811LSF53G": {
    id: "comp-K74L811LSF53G",
    props: {
      display: "flex",
      fontSize: "xl",
      ml: "4",
    },
    children: [
      "comp-K74L8Y2I2J5V4",
      "comp-K74L83QUJ55KZ",
      "comp-K74L8CNA98THU",
    ],
    type: "Box",
    parent: "comp-K74L6WFISOLG3",
    rootParentType: "Box",
  },
  "comp-K74L83QUJ55KZ": {
    id: "comp-K74L83QUJ55KZ",
    props: {
      children: "secret",
      color: "white",
      fontWeight: "bold",
    },
    children: [],
    type: "Text",
    parent: "comp-K74L811LSF53G",
    rootParentType: "Text",
  },
  "comp-K74L8CNA98THU": {
    id: "comp-K74L8CNA98THU",
    props: {
      children: "chakra",
      color: "white",
    },
    children: [],
    type: "Text",
    parent: "comp-K74L811LSF53G",
    rootParentType: "Text",
  },
  "comp-K74L8Y2I2J5V4": {
    id: "comp-K74L8Y2I2J5V4",
    props: {
      icon: "MoonIcon",
      color: "whatsapp.100",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74L811LSF53G",
    rootParentType: "Icon",
  },
  "comp-K74LBAD12N7N8": {
    id: "comp-K74LBAD12N7N8",
    props: {
      justifyContent: "center",
      alignItems: "center",
      ml: "10",
      mr: "4",
    },
    children: ["comp-K74LBPCL2U206", "comp-K74LBFTN7FVZR"],
    type: "Flex",
    parent: "comp-K74L6WFISOLG3",
    rootParentType: "Flex",
  },
  "comp-K74LBFTN7FVZR": {
    id: "comp-K74LBFTN7FVZR",
    props: {
      color: "teal",
      isChecked: true,
      size: "sm",
    },
    children: [],
    type: "Switch",
    parent: "comp-K74LBAD12N7N8",
    rootParentType: "Switch",
  },
  "comp-K74LBPCL2U206": {
    id: "comp-K74LBPCL2U206",
    props: {
      children: "Builder mode",
      color: "white",
      fontSize: "xs",
      pr: "2",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LBAD12N7N8",
    rootParentType: "Text",
  },
  "comp-K74LCUBUXNFY3": {
    id: "comp-K74LCUBUXNFY3",
    props: {
      children: "Code panel",
      color: "white",
      fontSize: "xs",
      pr: "2",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LCUBUZD53Y",
    rootParentType: "Text",
  },
  "comp-K74LCUBU9LHFQ": {
    id: "comp-K74LCUBU9LHFQ",
    props: {
      color: "teal",
      isChecked: true,
      size: "sm",
    },
    children: [],
    type: "Switch",
    parent: "comp-K74LCUBUZD53Y",
    rootParentType: "Switch",
  },
  "comp-K74LCUBUZD53Y": {
    id: "comp-K74LCUBUZD53Y",
    props: {
      justifyContent: "center",
      alignItems: "center",
    },
    children: ["comp-K74LCUBUXNFY3", "comp-K74LCUBU9LHFQ"],
    type: "Flex",
    parent: "comp-K74L6WFISOLG3",
    rootParentType: "Flex",
  },
  "comp-K74LFVLYTWR7H": {
    id: "comp-K74LFVLYTWR7H",
    props: {
      width: "15rem",
      backgroundColor: "#2e3748",
      m: "",
      p: "5",
      flexDirection: "column",
      height: "100%",
    },
    children: ["comp-K74LH4LGZPG3Q", "comp-K74LJ2RGGFSO8"],
    type: "Flex",
    parent: "comp-K74LORRCCHJDL",
    rootParentType: "Flex",
  },
  "comp-K74LH4LGZPG3Q": {
    id: "comp-K74LH4LGZPG3Q",
    props: {
      size: "sm",
      variant: "outline",
      backgroundColor: "gray.600",
      border: "none",
      placeholder: "Search components...",
    },
    children: [],
    type: "Input",
    parent: "comp-K74LFVLYTWR7H",
    rootParentType: "Input",
  },
  "comp-K74LJ2RGGFSO8": {
    id: "comp-K74LJ2RGGFSO8",
    props: {
      mt: "5",
    },
    children: [
      "comp-K74LJQGBRXK7V",
      "comp-K74LN1I4JX3W1",
      "comp-K74LN28WQ0U7I",
      "comp-K74LNLUX27J08",
      "comp-K74LNM59R5VQ2",
      "comp-K74LNMADR9K0Q",
      "comp-K74LNMEN8KNY1",
    ],
    type: "Stack",
    parent: "comp-K74LFVLYTWR7H",
    rootParentType: "Stack",
  },
  "comp-K74LJQGBRXK7V": {
    id: "comp-K74LJQGBRXK7V",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LJUTPCBAFB", "comp-K74LKHWKQF9E6"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LJUTPCBAFB": {
    id: "comp-K74LJUTPCBAFB",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LJQGBRXK7V",
    rootParentType: "Icon",
  },
  "comp-K74LKHWKQF9E6": {
    id: "comp-K74LKHWKQF9E6",
    props: {
      children: "Box",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LJQGBRXK7V",
    rootParentType: "Text",
  },
  "comp-K74LN1I49Q2D6": {
    id: "comp-K74LN1I49Q2D6",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LN1I4JX3W1",
    rootParentType: "Icon",
  },
  "comp-K74LN1I4K6K6U": {
    id: "comp-K74LN1I4K6K6U",
    props: {
      children: "Textarea",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LN1I4JX3W1",
    rootParentType: "Text",
  },
  "comp-K74LN1I4JX3W1": {
    id: "comp-K74LN1I4JX3W1",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LN1I49Q2D6", "comp-K74LN1I4K6K6U"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LN28W6SFUY": {
    id: "comp-K74LN28W6SFUY",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LN28WQ0U7I",
    rootParentType: "Icon",
  },
  "comp-K74LN28WJ5IBP": {
    id: "comp-K74LN28WJ5IBP",
    props: {
      children: "Avatar",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LN28WQ0U7I",
    rootParentType: "Text",
  },
  "comp-K74LN28WQ0U7I": {
    id: "comp-K74LN28WQ0U7I",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LN28W6SFUY", "comp-K74LN28WJ5IBP"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LNLUXPHO6M": {
    id: "comp-K74LNLUXPHO6M",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LNLUX27J08",
    rootParentType: "Icon",
  },
  "comp-K74LNLUX7SD0H": {
    id: "comp-K74LNLUX7SD0H",
    props: {
      children: "Avatar",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LNLUX27J08",
    rootParentType: "Text",
  },
  "comp-K74LNLUX27J08": {
    id: "comp-K74LNLUX27J08",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LNLUXPHO6M", "comp-K74LNLUX7SD0H"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LNM597JAOI": {
    id: "comp-K74LNM597JAOI",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LNM59R5VQ2",
    rootParentType: "Icon",
  },
  "comp-K74LNM59RM6C2": {
    id: "comp-K74LNM59RM6C2",
    props: {
      children: "Badge",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LNM59R5VQ2",
    rootParentType: "Text",
  },
  "comp-K74LNM59R5VQ2": {
    id: "comp-K74LNM59R5VQ2",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LNM597JAOI", "comp-K74LNM59RM6C2"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LNMAD8I86G": {
    id: "comp-K74LNMAD8I86G",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LNMADR9K0Q",
    rootParentType: "Icon",
  },
  "comp-K74LNMAD7BSAA": {
    id: "comp-K74LNMAD7BSAA",
    props: {
      children: "Tag",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LNMADR9K0Q",
    rootParentType: "Text",
  },
  "comp-K74LNMADR9K0Q": {
    id: "comp-K74LNMADR9K0Q",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LNMAD8I86G", "comp-K74LNMAD7BSAA"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LNMENCU4KP": {
    id: "comp-K74LNMENCU4KP",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74LNMEN8KNY1",
    rootParentType: "Icon",
  },
  "comp-K74LNMENV2U06": {
    id: "comp-K74LNMENV2U06",
    props: {
      children: "Chekbox",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LNMEN8KNY1",
    rootParentType: "Text",
  },
  "comp-K74LNMEN8KNY1": {
    id: "comp-K74LNMEN8KNY1",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74LNMENCU4KP", "comp-K74LNMENV2U06"],
    type: "Box",
    parent: "comp-K74LJ2RGGFSO8",
    rootParentType: "Box",
  },
  "comp-K74LORRCCHJDL": {
    id: "comp-K74LORRCCHJDL",
    props: {
      height: "100%",
    },
    children: [
      "comp-K74LFVLYTWR7H",
      "comp-K74LPAIMR0ECA",
      "comp-K74LPCLIHYI6L",
    ],
    type: "Flex",
    parent: "comp-root",
    rootParentType: "Flex",
  },
  "comp-K74LPAIMR0ECA": {
    id: "comp-K74LPAIMR0ECA",
    props: {
      width: "100%",
      height: "100%",
      p: "5",
    },
    children: ["comp-K74M9CCGRSDT1"],
    type: "Flex",
    parent: "comp-K74LORRCCHJDL",
    rootParentType: "Flex",
  },
  "comp-K74LPCLIHYI6L": {
    id: "comp-K74LPCLIHYI6L",
    props: {
      width: "17rem",
      height: "100%",
      backgroundColor: "white",
      justifyContent: "flex-start",
      flexDirection: "column",
    },
    children: [
      "comp-K74LYYQF91099",
      "comp-K74M27D1Q37CK",
      "comp-K74M4AXG5WJSX",
      "comp-K74M7L09GZDX4",
      "comp-K74M7RPHLYYCJ",
    ],
    type: "Flex",
    parent: "comp-K74LORRCCHJDL",
    rootParentType: "Flex",
  },
  "comp-K74LYYQF91099": {
    id: "comp-K74LYYQF91099",
    props: {
      bg: "yellow.100",
      p: "2",
      boxShadow: "sm",
    },
    children: ["comp-K74LZHHZT6RVX"],
    type: "Box",
    parent: "comp-K74LPCLIHYI6L",
    rootParentType: "Box",
  },
  "comp-K74LZHHZT6RVX": {
    id: "comp-K74LZHHZT6RVX",
    props: {
      children: "SimpleGrid",
      color: "yellow.800",
      fontWeight: "bold",
    },
    children: [],
    type: "Text",
    parent: "comp-K74LYYQF91099",
    rootParentType: "Text",
  },
  "comp-K74M27D1Q37CK": {
    id: "comp-K74M27D1Q37CK",
    props: {
      justifyContent: "flex-end",
      m: "",
      mt: "2",
    },
    children: [
      "comp-K74M2CH7IR4IT",
      "comp-K74M2TSIDQKT0",
      "comp-K74M2U4X3SQZX",
    ],
    type: "Flex",
    parent: "comp-K74LPCLIHYI6L",
    rootParentType: "Flex",
  },
  "comp-K74M2CH7IR4IT": {
    id: "comp-K74M2CH7IR4IT",
    props: {
      "aria-label": "icon",
      icon: "CopyIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M27D1Q37CK",
    rootParentType: "IconButton",
  },
  "comp-K74M2TSIDQKT0": {
    id: "comp-K74M2TSIDQKT0",
    props: {
      "aria-label": "icon",
      icon: "DeleteIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M27D1Q37CK",
    rootParentType: "IconButton",
  },
  "comp-K74M2U4X3SQZX": {
    id: "comp-K74M2U4X3SQZX",
    props: {
      "aria-label": "icon",
      icon: "RepeatIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M27D1Q37CK",
    rootParentType: "IconButton",
  },
  "comp-K74M4AXG5WJSX": {
    id: "comp-K74M4AXG5WJSX",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
      pr: "",
    },
    children: ["comp-K74M4I0N0ZGMZ", "comp-K74M4LQNKWGCQ"],
    type: "SimpleGrid",
    parent: "comp-K74LPCLIHYI6L",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M4I0N0ZGMZ": {
    id: "comp-K74M4I0N0ZGMZ",
    props: {
      children: "Columns",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M4AXG5WJSX",
    rootParentType: "Text",
  },
  "comp-K74M4LQNKWGCQ": {
    id: "comp-K74M4LQNKWGCQ",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M4AXG5WJSX",
    rootParentType: "Input",
  },
  "comp-K74M7L09GCMEA": {
    id: "comp-K74M7L09GCMEA",
    props: {
      children: "Spacing X",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M7L09GZDX4",
    rootParentType: "Text",
  },
  "comp-K74M7L09OF9HM": {
    id: "comp-K74M7L09OF9HM",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M7L09GZDX4",
    rootParentType: "Input",
  },
  "comp-K74M7L09GZDX4": {
    id: "comp-K74M7L09GZDX4",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
    },
    children: ["comp-K74M7L09GCMEA", "comp-K74M7L09OF9HM"],
    type: "SimpleGrid",
    parent: "comp-K74LPCLIHYI6L",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M7RPHZSJBU": {
    id: "comp-K74M7RPHZSJBU",
    props: {
      children: "Spacing Y",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M7RPHLYYCJ",
    rootParentType: "Text",
  },
  "comp-K74M7RPHJNL06": {
    id: "comp-K74M7RPHJNL06",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M7RPHLYYCJ",
    rootParentType: "Input",
  },
  "comp-K74M7RPHLYYCJ": {
    id: "comp-K74M7RPHLYYCJ",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
    },
    children: ["comp-K74M7RPHZSJBU", "comp-K74M7RPHJNL06"],
    type: "SimpleGrid",
    parent: "comp-K74LPCLIHYI6L",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M9CCGNQPHP": {
    id: "comp-K74M9CCGNQPHP",
    props: {
      icon: "MoonIcon",
      color: "whatsapp.100",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGSAWAU",
    rootParentType: "Icon",
  },
  "comp-K74M9CCGBL195": {
    id: "comp-K74M9CCGBL195",
    props: {
      children: "secret",
      color: "white",
      fontWeight: "bold",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGSAWAU",
    rootParentType: "Text",
  },
  "comp-K74M9CCGVYHML": {
    id: "comp-K74M9CCGVYHML",
    props: {
      children: "chakra",
      color: "white",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGSAWAU",
    rootParentType: "Text",
  },
  "comp-K74M9CCGSAWAU": {
    id: "comp-K74M9CCGSAWAU",
    props: {
      display: "flex",
      fontSize: "xl",
      ml: "4",
    },
    children: [
      "comp-K74M9CCGNQPHP",
      "comp-K74M9CCGBL195",
      "comp-K74M9CCGVYHML",
    ],
    type: "Box",
    parent: "comp-K74M9CCGUBSH1",
    rootParentType: "Box",
  },
  "comp-K74M9CCGDFLWX": {
    id: "comp-K74M9CCGDFLWX",
    props: {
      children: "Builder mode",
      color: "white",
      fontSize: "xs",
      pr: "2",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGPPQ74",
    rootParentType: "Text",
  },
  "comp-K74M9CCGM8KTG": {
    id: "comp-K74M9CCGM8KTG",
    props: {
      color: "teal",
      isChecked: true,
      size: "sm",
    },
    children: [],
    type: "Switch",
    parent: "comp-K74M9CCGPPQ74",
    rootParentType: "Switch",
  },
  "comp-K74M9CCGPPQ74": {
    id: "comp-K74M9CCGPPQ74",
    props: {
      justifyContent: "center",
      alignItems: "center",
      ml: "10",
      mr: "4",
    },
    children: ["comp-K74M9CCGDFLWX", "comp-K74M9CCGM8KTG"],
    type: "Flex",
    parent: "comp-K74M9CCGUBSH1",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGIEWKT": {
    id: "comp-K74M9CCGIEWKT",
    props: {
      children: "Code panel",
      color: "white",
      fontSize: "xs",
      pr: "2",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGWWDO1",
    rootParentType: "Text",
  },
  "comp-K74M9CCGNK2Z1": {
    id: "comp-K74M9CCGNK2Z1",
    props: {
      color: "teal",
      isChecked: true,
      size: "sm",
    },
    children: [],
    type: "Switch",
    parent: "comp-K74M9CCGWWDO1",
    rootParentType: "Switch",
  },
  "comp-K74M9CCGWWDO1": {
    id: "comp-K74M9CCGWWDO1",
    props: {
      justifyContent: "center",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGIEWKT", "comp-K74M9CCGNK2Z1"],
    type: "Flex",
    parent: "comp-K74M9CCGUBSH1",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGUBSH1": {
    id: "comp-K74M9CCGUBSH1",
    props: {
      backgroundColor: "#1a202c",
      p: "3",
    },
    children: [
      "comp-K74M9CCGSAWAU",
      "comp-K74M9CCGPPQ74",
      "comp-K74M9CCGWWDO1",
    ],
    type: "Flex",
    parent: "comp-K74M9CCGRSDT1",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGGZE9Q": {
    id: "comp-K74M9CCGGZE9Q",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGE9N4R",
    rootParentType: "Icon",
  },
  "comp-K74M9CCG5Q2OR": {
    id: "comp-K74M9CCG5Q2OR",
    props: {
      children: "Box",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGE9N4R",
    rootParentType: "Text",
  },
  "comp-K74M9CCGE9N4R": {
    id: "comp-K74M9CCGE9N4R",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGGZE9Q", "comp-K74M9CCG5Q2OR"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCG0S0RV": {
    id: "comp-K74M9CCG0S0RV",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGCUIE7",
    rootParentType: "Icon",
  },
  "comp-K74M9CCGT6O9V": {
    id: "comp-K74M9CCGT6O9V",
    props: {
      children: "Textarea",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGCUIE7",
    rootParentType: "Text",
  },
  "comp-K74M9CCGCUIE7": {
    id: "comp-K74M9CCGCUIE7",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCG0S0RV", "comp-K74M9CCGT6O9V"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCGPQ7C2": {
    id: "comp-K74M9CCGPQ7C2",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGP7TL5",
    rootParentType: "Icon",
  },
  "comp-K74M9CCG88SSV": {
    id: "comp-K74M9CCG88SSV",
    props: {
      children: "Avatar",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGP7TL5",
    rootParentType: "Text",
  },
  "comp-K74M9CCGP7TL5": {
    id: "comp-K74M9CCGP7TL5",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGPQ7C2", "comp-K74M9CCG88SSV"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCGEPP92": {
    id: "comp-K74M9CCGEPP92",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGIIVIY",
    rootParentType: "Icon",
  },
  "comp-K74M9CCGWS0H5": {
    id: "comp-K74M9CCGWS0H5",
    props: {
      children: "Avatar",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGIIVIY",
    rootParentType: "Text",
  },
  "comp-K74M9CCGIIVIY": {
    id: "comp-K74M9CCGIIVIY",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGEPP92", "comp-K74M9CCGWS0H5"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCG2CWCC": {
    id: "comp-K74M9CCG2CWCC",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGKXNSF",
    rootParentType: "Icon",
  },
  "comp-K74M9CCGKMT3N": {
    id: "comp-K74M9CCGKMT3N",
    props: {
      children: "Badge",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGKXNSF",
    rootParentType: "Text",
  },
  "comp-K74M9CCGKXNSF": {
    id: "comp-K74M9CCGKXNSF",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCG2CWCC", "comp-K74M9CCGKMT3N"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCGBHD01": {
    id: "comp-K74M9CCGBHD01",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCG7N53K",
    rootParentType: "Icon",
  },
  "comp-K74M9CCG2ROC8": {
    id: "comp-K74M9CCG2ROC8",
    props: {
      children: "Tag",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCG7N53K",
    rootParentType: "Text",
  },
  "comp-K74M9CCG7N53K": {
    id: "comp-K74M9CCG7N53K",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGBHD01", "comp-K74M9CCG2ROC8"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCGJS0IN": {
    id: "comp-K74M9CCGJS0IN",
    props: {
      icon: "DragHandleIcon",
      color: "gray.300",
      fontSize: "sm",
      mr: "2",
    },
    children: [],
    type: "Icon",
    parent: "comp-K74M9CCGV27GO",
    rootParentType: "Icon",
  },
  "comp-K74M9CCGRFTZY": {
    id: "comp-K74M9CCGRFTZY",
    props: {
      children: "Chekbox",
      fontSize: "sm",
      color: "gray.300",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGV27GO",
    rootParentType: "Text",
  },
  "comp-K74M9CCGV27GO": {
    id: "comp-K74M9CCGV27GO",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    children: ["comp-K74M9CCGJS0IN", "comp-K74M9CCGRFTZY"],
    type: "Box",
    parent: "comp-K74M9CCG9EXJZ",
    rootParentType: "Box",
  },
  "comp-K74M9CCG9EXJZ": {
    id: "comp-K74M9CCG9EXJZ",
    props: {
      mt: "5",
    },
    children: [
      "comp-K74M9CCGE9N4R",
      "comp-K74M9CCGCUIE7",
      "comp-K74M9CCGP7TL5",
      "comp-K74M9CCGIIVIY",
      "comp-K74M9CCGKXNSF",
      "comp-K74M9CCG7N53K",
      "comp-K74M9CCGV27GO",
    ],
    type: "Stack",
    parent: "comp-K74M9CCG94DEQ",
    rootParentType: "Stack",
  },
  "comp-K74M9CCG94DEQ": {
    id: "comp-K74M9CCG94DEQ",
    props: {
      width: "15rem",
      backgroundColor: "#2e3748",
      m: "",
      p: "5",
      flexDirection: "column",
      height: "100%",
    },
    children: ["comp-K74MDRB8N3GRS", "comp-K74M9CCG9EXJZ"],
    type: "Flex",
    parent: "comp-K74M9CCGQDXNZ",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGVB5K9": {
    id: "comp-K74M9CCGVB5K9",
    props: {
      width: "100%",
      height: "100%",
    },
    children: [],
    type: "Flex",
    parent: "comp-K74M9CCGQDXNZ",
    rootParentType: "Flex",
  },
  "comp-K74M9CCG9YO15": {
    id: "comp-K74M9CCG9YO15",
    props: {
      children: "SimpleGrid",
      color: "yellow.800",
      fontWeight: "bold",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGZGAAN",
    rootParentType: "Text",
  },
  "comp-K74M9CCGZGAAN": {
    id: "comp-K74M9CCGZGAAN",
    props: {
      bg: "yellow.100",
      p: "2",
      boxShadow: "sm",
    },
    children: ["comp-K74M9CCG9YO15"],
    type: "Box",
    parent: "comp-K74M9CCG9WW9R",
    rootParentType: "Box",
  },
  "comp-K74M9CCGSW3SU": {
    id: "comp-K74M9CCGSW3SU",
    props: {
      "aria-label": "icon",
      icon: "CopyIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M9CCGNMBYL",
    rootParentType: "IconButton",
  },
  "comp-K74M9CCGTKCJ7": {
    id: "comp-K74M9CCGTKCJ7",
    props: {
      "aria-label": "icon",
      icon: "DeleteIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M9CCGNMBYL",
    rootParentType: "IconButton",
  },
  "comp-K74M9CCGGX02O": {
    id: "comp-K74M9CCGGX02O",
    props: {
      "aria-label": "icon",
      icon: "RepeatIcon",
      size: "xs",
      variant: "ghost",
      colorScheme: "gray",
    },
    children: [],
    type: "IconButton",
    parent: "comp-K74M9CCGNMBYL",
    rootParentType: "IconButton",
  },
  "comp-K74M9CCGNMBYL": {
    id: "comp-K74M9CCGNMBYL",
    props: {
      justifyContent: "flex-end",
      m: "",
      mt: "2",
    },
    children: [
      "comp-K74M9CCGSW3SU",
      "comp-K74M9CCGTKCJ7",
      "comp-K74M9CCGGX02O",
    ],
    type: "Flex",
    parent: "comp-K74M9CCG9WW9R",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGF4AWI": {
    id: "comp-K74M9CCGF4AWI",
    props: {
      children: "Columns",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGGMJ6O",
    rootParentType: "Text",
  },
  "comp-K74M9CCGX9HAN": {
    id: "comp-K74M9CCGX9HAN",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M9CCGGMJ6O",
    rootParentType: "Input",
  },
  "comp-K74M9CCGGMJ6O": {
    id: "comp-K74M9CCGGMJ6O",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
      pr: "",
    },
    children: ["comp-K74M9CCGF4AWI", "comp-K74M9CCGX9HAN"],
    type: "SimpleGrid",
    parent: "comp-K74M9CCG9WW9R",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M9CCGT5UYZ": {
    id: "comp-K74M9CCGT5UYZ",
    props: {
      children: "Spacing X",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCGZMAHR",
    rootParentType: "Text",
  },
  "comp-K74M9CCGST1K3": {
    id: "comp-K74M9CCGST1K3",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M9CCGZMAHR",
    rootParentType: "Input",
  },
  "comp-K74M9CCGZMAHR": {
    id: "comp-K74M9CCGZMAHR",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
    },
    children: ["comp-K74M9CCGT5UYZ", "comp-K74M9CCGST1K3"],
    type: "SimpleGrid",
    parent: "comp-K74M9CCG9WW9R",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M9CCG0N30O": {
    id: "comp-K74M9CCG0N30O",
    props: {
      children: "Spacing Y",
      fontSize: "xs",
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "gray.500",
    },
    children: [],
    type: "Text",
    parent: "comp-K74M9CCG6F4OJ",
    rootParentType: "Text",
  },
  "comp-K74M9CCGBJE71": {
    id: "comp-K74M9CCGBJE71",
    props: {
      size: "sm",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M9CCG6F4OJ",
    rootParentType: "Input",
  },
  "comp-K74M9CCG6F4OJ": {
    id: "comp-K74M9CCG6F4OJ",
    props: {
      columns: 2,
      spacingX: 1,
      spacingY: 1,
      p: "1",
      pl: "2",
    },
    children: ["comp-K74M9CCG0N30O", "comp-K74M9CCGBJE71"],
    type: "SimpleGrid",
    parent: "comp-K74M9CCG9WW9R",
    rootParentType: "SimpleGrid",
  },
  "comp-K74M9CCG9WW9R": {
    id: "comp-K74M9CCG9WW9R",
    props: {
      width: "17rem",
      height: "100%",
      backgroundColor: "white",
      justifyContent: "flex-start",
      flexDirection: "column",
    },
    children: [
      "comp-K74M9CCGZGAAN",
      "comp-K74M9CCGNMBYL",
      "comp-K74M9CCGGMJ6O",
      "comp-K74M9CCGZMAHR",
      "comp-K74M9CCG6F4OJ",
    ],
    type: "Flex",
    parent: "comp-K74M9CCGQDXNZ",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGQDXNZ": {
    id: "comp-K74M9CCGQDXNZ",
    props: {
      height: "100%",
    },
    children: [
      "comp-K74M9CCG94DEQ",
      "comp-K74M9CCGVB5K9",
      "comp-K74M9CCG9WW9R",
    ],
    type: "Flex",
    parent: "comp-K74M9CCGRSDT1",
    rootParentType: "Flex",
  },
  "comp-K74M9CCGRSDT1": {
    id: "comp-K74M9CCGRSDT1",
    props: {
      width: "100%",
      height: "100%",
      display: "flex",
      flexDirection: "column",
      color: "",
      backgroundColor: "gray.100",
    },
    children: ["comp-K74M9CCGUBSH1", "comp-K74M9CCGQDXNZ"],
    type: "Flex",
    parent: "comp-K74LPAIMR0ECA",
    rootParentType: "Flex",
  },
  "comp-K74MDRB8N3GRS": {
    id: "comp-K74MDRB8N3GRS",
    props: {
      size: "sm",
      variant: "outline",
      backgroundColor: "gray.600",
      border: "none",
      placeholder: "Search components...",
    },
    children: [],
    type: "Input",
    parent: "comp-K74M9CCG94DEQ",
    rootParentType: "Input",
  },
};

export const airbnbCard: IComponents = {
  root: {
    id: "root",
    parent: "root",
    type: "Box",
    children: ["comp-1580479567"],
    props: {},
  },
  "comp-root": {
    id: "comp-root",
    props: {
      bg: "#ffffff",
      borderRadius: "lg",
      width: "sm",
      minHeight: "sm",
      border: "1px solid lightgrey",
      overflow: "hidden",
    },
    children: ["comp-1580479581", "comp-1580479627"],
    type: "Box",
    parent: "root",
  },
  "comp-1580479581": {
    id: "comp-1580479581",
    props: {},
    children: ["comp-1580479588"],
    type: "Box",
    parent: "comp-root",
  },
  "comp-1580479588": {
    id: "comp-1580479588",
    props: {
      size: "100px",
      fallbackSrc: "https://via.placeholder.com/150",
      src:
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      width: "100%",
      height: "auto",
      minHeight: "245px",
    },
    children: [],
    type: "Image",
    parent: "comp-1580479581",
  },
  "comp-1580479627": {
    id: "comp-1580479627",
    props: {
      p: "5",
      pb: "8",
    },
    children: [
      "comp-1580479631",
      "comp-1580479743",
      "comp-1580479791",
      "comp-1580479811",
    ],
    type: "Box",
    parent: "comp-root",
  },
  "comp-1580479631": {
    id: "comp-1580479631",
    props: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      mb: "1",
      flexDirection: "row",
    },
    children: ["comp-1580479639", "comp-1580479654"],
    type: "Box",
    parent: "comp-1580479627",
  },
  "comp-1580479639": {
    id: "comp-1580479639",
    props: {
      children: "NEW",
      variant: "subtle",
      colorScheme: "teal",
      mr: "2",
      borderRadius: "lg",
      pl: "2",
      pr: "2",
    },
    children: [],
    type: "Badge",
    parent: "comp-1580479631",
  },
  "comp-1580479654": {
    id: "comp-1580479654",
    props: {
      children: "3 BEDS • 2 BATHS",
      color: "gray.500",
      fontSize: "xs",
    },
    children: [],
    type: "Text",
    parent: "comp-1580479631",
  },
  "comp-1580479743": {
    id: "comp-1580479743",
    props: {
      children: "Modern home in city center",
      fontWeight: "bold",
      fontSize: "xl",
    },
    children: [],
    type: "Text",
    parent: "comp-1580479627",
  },
  "comp-1580479791": {
    id: "comp-1580479791",
    props: {
      children: "$119/night",
      fontSize: "sm",
      mb: "3",
    },
    children: [],
    type: "Text",
    parent: "comp-1580479627",
  },
  "comp-1580479811": {
    id: "comp-1580479811",
    props: {
      display: "flex",
      alignItems: "center",
      mb: "",
      flexDirection: "row",
      justifyContent: "flex-start",
    },
    children: ["comp-1580479816", "comp-1580479832", "comp-1580479862"],
    type: "Box",
    parent: "comp-1580479627",
  },
  "comp-1580479816": {
    id: "comp-1580479816",
    props: {
      icon: "StarIcon",
      color: "yellow.400",
      mr: "1",
    },
    children: [],
    type: "Icon",
    parent: "comp-1580479811",
  },
  "comp-1580479832": {
    id: "comp-1580479832",
    props: {
      children: "4.84",
      fontWeight: "bold",
      mr: "1",
    },
    children: [],
    type: "Text",
    parent: "comp-1580479811",
  },
  "comp-1580479862": {
    id: "comp-1580479862",
    props: {
      children: "(190)",
      fontSize: "sm",
    },
    children: [],
    type: "Text",
    parent: "comp-1580479811",
  },
};

export const productHunt: IComponents = {
  root: {
    id: "root",
    parent: "root",
    type: "Box",
    children: ["comp-root", "comp-K6IB1AANA79Y6"],
    props: {
      backgroundColor: "#f3f3f3",
    },
  },
  "comp-root": {
    id: "comp-root",
    props: {
      backgroundColor: "white",
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      p: "5",
      boxShadow: "sm",
    },
    children: ["comp-K6IAUUX80CXD6", "comp-K6IAWV0WFDNW7"],
    type: "Box",
    parent: "root",
    rootParentType: "Box",
  },
  "comp-K6IAR7ZINSAGW": {
    id: "comp-K6IAR7ZINSAGW",
    props: {
      children: "P",
      color: "white",
      fontSize: "3xl",
    },
    children: [],
    type: "Text",
    parent: "comp-K6IAQM3L5NR7W",
    rootParentType: "Text",
  },
  "comp-K6IASJJIS6V77": {
    id: "comp-K6IASJJIS6V77",
    props: {
      size: "md",
      name: "P",
      fontSize: "3xl",
      backgroundColor: "orange.500",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IAUUX80CXD6",
    rootParentType: "Avatar",
  },
  "comp-K6IATGONJ9KDR": {
    children: [],
    type: "InputLeftAddon",
    parent: "comp-K6IATGON2EINZ",
    id: "comp-K6IATGONJ9KDR",
    props: {
      children: "Emai",
    },
    rootParentType: "Input",
  },
  "comp-K6IATGONWXKQC": {
    children: [],
    type: "Input",
    parent: "comp-K6IATGON2EINZ",
    id: "comp-K6IATGONWXKQC",
    props: {
      size: "md",
      as: "input",
      variant: "outline",
      isFullWidth: true,
      focusBorderColor: "blue.500",
      errorBorderColor: "red.500",
    },
    rootParentType: "Input",
  },
  "comp-K6IATGON4BXKS": {
    children: ["comp-K6IATGOOHID42"],
    type: "InputRightElement",
    parent: "comp-K6IATGON2EINZ",
    id: "comp-K6IATGON4BXKS",
    props: {},
    rootParentType: "Input",
  },
  "comp-K6IATGOOHID42": {
    children: [],
    type: "Icon",
    parent: "comp-K6IATGON4BXKS",
    id: "comp-K6IATGOOHID42",
    props: {
      icon: "EmailIcon",
    },
    rootParentType: "Input",
  },
  "comp-K6IATQU9VOYJ0": {
    id: "comp-K6IATQU9VOYJ0",
    props: {
      display: "block",
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "flex-start",
    },
    children: ["comp-K6IATS4IZ7KD8"],
    type: "InputLeftElement",
    parent: "comp-K6IATKWZ5I33A",
    rootParentType: "Input",
  },
  "comp-K6IATS4IZ7KD8": {
    id: "comp-K6IATS4IZ7KD8",
    props: {
      size: "md",
      as: "input",
      variant: "outline",
      isFullWidth: true,
      focusBorderColor: "blue.500",
      errorBorderColor: "red.500",
    },
    children: [],
    type: "Input",
    parent: "comp-K6IATQU9VOYJ0",
    rootParentType: "Input",
  },
  "comp-K6IAUUX80CXD6": {
    id: "comp-K6IAUUX80CXD6",
    props: {
      isInline: true,
      isReversed: false,

      alignItems: "center",
      spacing: "3",
    },
    children: [
      "comp-K6IASJJIS6V77",
      "comp-K6IAV6E1J71L7",
      "comp-K6IAVUTA4NRKO",
      "comp-K6IAVYIJ6HPB2",
      "comp-K6IAW325BUPFG",
    ],
    type: "Stack",
    parent: "comp-root",
    rootParentType: "Stack",
  },
  "comp-K6IAV6E1J71L7": {
    id: "comp-K6IAV6E1J71L7",
    props: {
      size: "md",
      as: "input",
      variant: "outline",
      isFullWidth: true,
      focusBorderColor: "blue.500",
      errorBorderColor: "red.500",
      placeholder: "Discover your next favorite thing.",
    },
    children: [],
    type: "Input",
    parent: "comp-K6IAUUX80CXD6",
    rootParentType: "Input",
  },
  "comp-K6IAVUTA4NRKO": {
    id: "comp-K6IAVUTA4NRKO",
    props: {
      children: "Deals",
      color: "gray.500",
    },
    children: [],
    type: "Link",
    parent: "comp-K6IAUUX80CXD6",
    rootParentType: "Link",
  },
  "comp-K6IAVYIJ6HPB2": {
    id: "comp-K6IAVYIJ6HPB2",
    props: {
      children: "Jobs",
      color: "gray.500",
    },
    children: [],
    type: "Link",
    parent: "comp-K6IAUUX80CXD6",
    rootParentType: "Link",
  },
  "comp-K6IAW325BUPFG": {
    id: "comp-K6IAW325BUPFG",
    props: {
      children: "Makers",
      color: "gray.500",
    },
    children: [],
    type: "Link",
    parent: "comp-K6IAUUX80CXD6",
    rootParentType: "Link",
  },
  "comp-K6IAWV0WFDNW7": {
    id: "comp-K6IAWV0WFDNW7",
    props: {},
    children: ["comp-K6IAX6IXQ7CAC"],
    type: "Stack",
    parent: "comp-root",
    rootParentType: "Stack",
  },
  "comp-K6IAX6IXQ7CAC": {
    id: "comp-K6IAX6IXQ7CAC",
    props: {
      size: "md",
      src:
        "https://pbs.twimg.com/profile_images/1227316457845018626/8-B-ZDL8_400x400.jpg",
    },
    children: ["comp-K6IAYZAIA7RJT"],
    type: "Avatar",
    parent: "comp-K6IAWV0WFDNW7",
    rootParentType: "Avatar",
  },
  "comp-K6IAYZAIA7RJT": {
    id: "comp-K6IAYZAIA7RJT",
    props: {
      bg: "green.500",
      size: "1.25em",
      borderColor: "white",
    },
    children: [],
    type: "AvatarBadge",
    parent: "comp-K6IAX6IXQ7CAC",
    rootParentType: "Avatar",
  },
  "comp-K6IB0ZX2RFMWK": {
    id: "comp-K6IB0ZX2RFMWK",
    props: {
      width: "lg",
    },
    children: ["comp-K6IB1HE13Y7BO", "comp-K6IB3I12GRYPN"],
    type: "Stack",
    parent: "comp-K6IB1AANA79Y6",
    rootParentType: "Stack",
  },
  "comp-K6IB1AANA79Y6": {
    id: "comp-K6IB1AANA79Y6",
    props: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      justifyContent: "flex-start",
      mt: "",
      p: "10",
    },
    children: ["comp-K6IB0ZX2RFMWK"],
    type: "Flex",
    parent: "root",
    rootParentType: "Flex",
  },
  "comp-K6IB1HE13Y7BO": {
    id: "comp-K6IB1HE13Y7BO",
    props: {
      size: "lg",
      as: "h2",
      lineHeight: "shorter",
      fontWeight: "bold",
      fontFamily: "heading",
      children: "Today",
    },
    children: [],
    type: "Heading",
    parent: "comp-K6IB0ZX2RFMWK",
    rootParentType: "Heading",
  },
  "comp-K6IB3I12GRYPN": {
    id: "comp-K6IB3I12GRYPN",
    props: {
      backgroundColor: "white",
      border: "",
      borderRadius: "lg",
      p: "5",
    },
    children: ["comp-K6IB42UQBXOB8"],
    type: "Stack",
    parent: "comp-K6IB0ZX2RFMWK",
    rootParentType: "Stack",
  },
  "comp-K6IB42UQBXOB8": {
    id: "comp-K6IB42UQBXOB8",
    props: {
      isInline: true,

      spacing: "2",
      alignItems: "center",
    },
    children: ["comp-K6IB45QVR3QMY", "comp-K6IB6HDI4V5B0"],
    type: "Stack",
    parent: "comp-K6IB3I12GRYPN",
    rootParentType: "Stack",
  },
  "comp-K6IB45QVR3QMY": {
    id: "comp-K6IB45QVR3QMY",
    props: {
      height: "80px",
      width: "80px",
      fallbackSrc: "https://via.placeholder.com/150",
      src:
        "https://user-images.githubusercontent.com/1102595/74273767-41168880-4d11-11ea-8f7f-3fb7a02624ea.gif",
      mr: "2",
    },
    children: [],
    type: "Image",
    parent: "comp-K6IB42UQBXOB8",
    rootParentType: "Image",
  },
  "comp-K6IB6HDI4V5B0": {
    id: "comp-K6IB6HDI4V5B0",
    props: {
      spacing: "0",
    },
    children: [
      "comp-K6IB6NC6WYM4M",
      "comp-K6IB7CDZP06DC",
      "comp-K6IB9PY4ED4M3",
    ],
    type: "Stack",
    parent: "comp-K6IB42UQBXOB8",
    rootParentType: "Stack",
  },
  "comp-K6IB6NC6WYM4M": {
    id: "comp-K6IB6NC6WYM4M",
    props: {
      children: "Open Chakra",
      fontSize: "lg",
      color: "gray.700",
    },
    children: [],
    type: "Text",
    parent: "comp-K6IB6HDI4V5B0",
    rootParentType: "Text",
  },
  "comp-K6IB7CDZP06DC": {
    id: "comp-K6IB7CDZP06DC",
    props: {
      children: "React visual editor: create UI with ease!",
      fontSize: "sm",
      color: "blackAlpha.700",
    },
    children: [],
    type: "Text",
    parent: "comp-K6IB6HDI4V5B0",
    rootParentType: "Text",
  },
  "comp-K6IB9PY4ED4M3": {
    id: "comp-K6IB9PY4ED4M3",
    props: {
      max: 4,
      spacing: -3,
      size: "xs",
      p: "",
      pl: "4",
      mt: "2",
    },
    children: [
      "comp-K6IB9SZ4T5MC3",
      "comp-K6IBA48KCVG5Y",
      "comp-K6IBA7B14LO5W",
      "comp-K6IBAM0EEARD9",
      "comp-K6IBAQN0DSH33",
    ],
    type: "AvatarGroup",
    parent: "comp-K6IB6HDI4V5B0",
    rootParentType: "Avatar",
  },
  "comp-K6IB9SZ4T5MC3": {
    id: "comp-K6IB9SZ4T5MC3",
    props: {
      size: "xs",
      name: "Ba Adrie",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IB9PY4ED4M3",
    rootParentType: "Avatar",
  },
  "comp-K6IBA48KCVG5Y": {
    id: "comp-K6IBA48KCVG5Y",
    props: {
      size: "xs",
      name: "to tot",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IB9PY4ED4M3",
    rootParentType: "Avatar",
  },
  "comp-K6IBA7B14LO5W": {
    id: "comp-K6IBA7B14LO5W",
    props: {
      size: "xs",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IB9PY4ED4M3",
    rootParentType: "Avatar",
  },
  "comp-K6IBAM0EEARD9": {
    id: "comp-K6IBAM0EEARD9",
    props: {
      size: "xs",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IB9PY4ED4M3",
    rootParentType: "Avatar",
  },
  "comp-K6IBAQN0DSH33": {
    id: "comp-K6IBAQN0DSH33",
    props: {
      size: "md",
    },
    children: [],
    type: "Avatar",
    parent: "comp-K6IB9PY4ED4M3",
    rootParentType: "Avatar",
  },
};
